### PR TITLE
fixed issues #46: the double tap problem and 2-fingers zoom problem u…

### PR DESCRIPTION
**Pull request by paladinzyh**
…nder android low version

### CODE REVIEW

**Comment by sandstrom** [comment]
Thanks @paladinzyh! Can you just briefly explain how these two changes work and why?

@RookieDouby I don't have access to a lot of different devices. Would you like to test the code in this PR and see if it solves the problem you had?

**Comment by paladinzyh** [comment]
1. 2-finger zooming failure problem：




“On Android ICS if no preventDefault is called on touchstart or the first touchmove, further touchmove events and the touchend will not be fired. ”




so I added preventDefault function. it worked




see details:

https://blog.mobiscroll.com/working-with-touch-events/

http://wilsonpage.co.uk/touch-events-in-chrome-android/




2. double click failure problem：




The original code will trigger touchmove after double clicked under android 4.x,but it should not be triggered,  touchmove will finally trigger stopAnimation function. the animation of zooming will stop.  then the problem occurred.   




And I find this solution:  

setTimeout(function () { cancelEvent(event) });

then touchmove event wasn’t triggered, it worked.




but to be honest  I don’t know why  : )




At 2017-09-07 19:15:13, "sandstrom" <notifications@github.com> wrote:


Thanks @paladinzyh! Can you just briefly explain how these two changes work and why?

@RookieDouby I don't have access to a lot of different devices. Would you like to test the code in this PR and see if it solves the problem you had?

**Comment by sandstrom** [comment]
Alright, thanks for explaining @paladinzyh. I'm not comfortable adding the `setTimeout` if we cannot describe why it works.

I know it's a lot to ask for, but if you could record the two issues (separately) and add to this issue that would be very helpful.

https://www.quora.com/Is-there-an-app-for-Android-that-lets-you-record-on-screen-video-and-save-it-as-animated-GIF

**Comment by sandstrom** [comment]
Hey @paladinzyh! Would you like to test this branch and see if it fixes the issue you had?

https://github.com/manuelstofer/pinchzoom/pull/52

**Comment by sandstrom** [comment]
I'm going to close this issue now, since I think it's fixed on master. Happy to re-open if I'm wrong!

@paladinzyh Thanks for working on this, much appreciated! 🎖

**Pull request closed without merging**
