### PR TITLE
Feature: add useDoubleTap option.

### PR DESCRIPTION
**Pull request by LorenzoLotti**
This new `useDoubleTap` option permits to disable the detection of double tap gestures. By default it will be set on `true` to guarantee backward compatibility.

I noticed that the `master` branch isn't up to date with the latest release and that the code inside it isn't stable, therefore I developed this feature on top of the version 2.3.5

### CODE REVIEW

**Comment by LorenzoLotti** [comment]
Conflicts are resolved, but at the current state `master` isn't ready for a release, the code still doesn't work properly

**Comment by LorenzoLotti** [comment]
After reading the changes of older pull requests, I think that the one which introduced said bugs on touchscreens is #133

It was presumably tested only on a pointer based environment and this led to bugs on touchscreen ones.

**Comment by sandstrom** [comment]
@LorenzoLotti Thanks!

How extensively have you tested these change?

What devices/browsers?

**Comment by LorenzoLotti** [comment]
Hi @sandstrom, I tested the feature both on pointer and touchscreen environments (a PC and a smartphone) with the following browsers:

- Chrome 120.0.6099.217
- Chrome Mobile 120.0.6099.210
- Firefox 121.0.1
- Firefox Mobile 121.1.0
- Edge 120.0.2210.133

I want to further clarify that the tests were made before e51307e, i.e. on the latest release (2.3.5) + my changes. As I already said in another comment, `master` is unstable due to bugs introduced with PRs (presumably #133) that came after the 2.3.5 release.

**Comment by sandstrom** [comment]
Great, thanks for letting me know! I'm not in a position to test any new functionality, so that's why I'm asking.

That's also why I'm somewhat reluctant to merge new things, to avoid introducing bugs.

Before I can review this, it needs to be a clean commit (or several) on top of master. No changes to package.json or package lock unless it's related to this PR.

**Review by sandstrom — APPROVED** [review]

**Comment by LorenzoLotti** [comment]
Thanks! As for those issues in the master branch, I'm considering to provide some well-tested fixes with new PRs. If you agree, we could then proceed with a new release at your convenience.

**Pull request merged**
