### PR TITLE
feat: add onInit callback

### LINKED ISSUE #103: Add onInit callback
I want to make a smooth appearance after initialization and this callback would be very helpful

### PR DESCRIPTION
**Pull request by avdeev**
Closes #103

### CODE REVIEW

**Comment by sandstrom** [comment]
@avdeev Thanks for contributing!

1. Can you explain with 1-2 sentences (here) in what case this would be useful? I don't understand what "smooth appearance after initialization" means. CSS animation? Something else?

2. Need to update this file too:
https://github.com/manuelstofer/pinchzoom/blob/master/src/pinch-zoom.d.ts

**Comment by avdeev** [comment]
@sandstrom Hi Alexander! Thank you for the quick answer!

I updated typings.

Yes, I mean CSS animation like this.

```coffeescript
new PinchZoom.default @$el.find('.img')[0],
  onInit: (object) -> $(object.el).addClass 'img_initialized'
```

```scss
.img {
  opacity: 0;
  transition: opacity 0.15s ease-out;

  &_initialized {
    opacity: 1;
  }
}
```

In my case I have the flash of the layout during library initialization. With this trick users will be able to hide image before and show it after initialization completed.

**Comment by sandstrom** [comment]
@avdeev Wouldn't something like this work?

```js
# alt 1
let myInstance = new PinchZoom(document.querySelector('div#foo'));
myInstance.el.classList.add('img_initialized');

# alt 2
let myEl = document.querySelector('div#foo');
new PinchZoom(myEl);
myEl.classList.add('img_initialized');
```

**Comment by avdeev** [comment]
@sandstrom Yes, you are right. I close the issue.

**Pull request closed without merging**
